--------------------------------------------------------
--  DDL for Table SMARTCAPTAR_APPROVED
--------------------------------------------------------

  CREATE TABLE "CAPTAR"."SMARTCAPTAR_APPROVED" 
   (	"CABLENUM" VARCHAR2(9 BYTE), 
	"CABLETYPE" VARCHAR2(15 BYTE), 
	"JOBNUM" VARCHAR2(10 BYTE), 
	"ENTEREDBY" VARCHAR2(12 BYTE), 
	"DATEENT" TIMESTAMP (6), 
	"FUNC" VARCHAR2(120 BYTE), 
	"ACTIONREQ" VARCHAR2(1 BYTE), 
	"SYSTEM" VARCHAR2(50 BYTE), 
	"LENGTH" VARCHAR2(20 BYTE), 
	"ROUTING" VARCHAR2(1000 BYTE), 
	"LIST_NO" VARCHAR2(20 BYTE), 
	"DWGNUM" VARCHAR2(200 BYTE), 
	"CABLEINV_ID" VARCHAR2(20 BYTE), 
	"CREATED_BY" VARCHAR2(30 BYTE), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(30 BYTE), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"DRAWING_TITLE" VARCHAR2(80 BYTE), 
	"STATUS" VARCHAR2(9 BYTE), 
	"AREACODE" VARCHAR2(20 BYTE), 
	"ORIGIN_LOC" VARCHAR2(20 BYTE), 
	"ORIGIN_RACK" VARCHAR2(40 BYTE), 
	"ORIGIN_SIDE" VARCHAR2(4 BYTE), 
	"ORIGIN_ELE" VARCHAR2(20 BYTE), 
	"ORIGIN_SLOT" VARCHAR2(6 BYTE), 
	"ORIGIN_CONNUM" VARCHAR2(30 BYTE), 
	"ORIGIN_PINLIST" VARCHAR2(16 BYTE), 
	"ORIGIN_CONNTYPE" VARCHAR2(9 BYTE), 
	"ORIGIN_STATION" VARCHAR2(20 BYTE), 
	"ORIGIN_INSTR" VARCHAR2(3 BYTE), 
	"STATION_OLD" VARCHAR2(6 BYTE), 
	"APPROVERS" VARCHAR2(4000 BYTE), 
	"DEST_LOC" VARCHAR2(20 BYTE), 
	"DEST_RACK" VARCHAR2(40 BYTE), 
	"DEST_SIDE" VARCHAR2(4 BYTE), 
	"DEST_ELE" VARCHAR2(20 BYTE), 
	"DEST_SLOT" VARCHAR2(6 BYTE), 
	"DEST_CONNUM" VARCHAR2(30 BYTE), 
	"DEST_PINLIST" VARCHAR2(16 BYTE), 
	"DEST_CONNTYPE" VARCHAR2(9 BYTE), 
	"DEST_STATION" VARCHAR2(20 BYTE), 
	"DEST_INSTR" VARCHAR2(3 BYTE), 
	"FORMDEV_NAME" VARCHAR2(20 BYTE), 
	"USERID_LIST_TITLE" VARCHAR2(20 BYTE), 
	"PHASE" VARCHAR2(20 BYTE), 
	"BEAM_AREA" VARCHAR2(20 BYTE), 
	"SECTOR_GROUP" VARCHAR2(20 BYTE), 
	"SECTOR_AREA_SOURCE" VARCHAR2(20 BYTE), 
	"SECTOR_AREA_DEST" VARCHAR2(20 BYTE), 
	"PENETRATION" VARCHAR2(20 BYTE), 
	"PENETRATION_2" VARCHAR2(20 BYTE), 
	"MIN_LENGTH" VARCHAR2(20 BYTE), 
	"MAX_LENGTH" VARCHAR2(20 BYTE), 
	"ADDNL_LENGTH" VARCHAR2(20 BYTE), 
	"REVISION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAPTAR_DATA" ;
--------------------------------------------------------
--  DDL for Table SMARTCAPTAR_COMPATIBILITY
--------------------------------------------------------

  CREATE TABLE "CAPTAR"."SMARTCAPTAR_COMPATIBILITY" 
   (	"CABLETYPE" VARCHAR2(15 BYTE), 
	"COMPAT" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAPTAR_DATA" ;
--------------------------------------------------------
--  DDL for Table SMARTCAPTAR_HISTORY
--------------------------------------------------------

  CREATE TABLE "CAPTAR"."SMARTCAPTAR_HISTORY" 
   (	"CABLENUM" VARCHAR2(9 BYTE), 
	"CABLETYPE" VARCHAR2(15 BYTE), 
	"JOBNUM" VARCHAR2(10 BYTE), 
	"ENTEREDBY" VARCHAR2(12 BYTE), 
	"DATEENT" TIMESTAMP (6), 
	"FUNC" VARCHAR2(120 BYTE), 
	"ACTIONREQ" VARCHAR2(1 BYTE), 
	"SYSTEM" VARCHAR2(50 BYTE), 
	"LENGTH" VARCHAR2(20 BYTE), 
	"ROUTING" VARCHAR2(1000 BYTE), 
	"LIST_NO" VARCHAR2(20 BYTE), 
	"DWGNUM" VARCHAR2(200 BYTE), 
	"CABLEINV_ID" VARCHAR2(20 BYTE), 
	"CREATED_BY" VARCHAR2(30 BYTE), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(30 BYTE), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"DRAWING_TITLE" VARCHAR2(80 BYTE), 
	"STATUS" VARCHAR2(9 BYTE), 
	"AREACODE" VARCHAR2(20 BYTE), 
	"ORIGIN_LOC" VARCHAR2(20 BYTE), 
	"ORIGIN_RACK" VARCHAR2(40 BYTE), 
	"ORIGIN_SIDE" VARCHAR2(4 BYTE), 
	"ORIGIN_ELE" VARCHAR2(20 BYTE), 
	"ORIGIN_SLOT" VARCHAR2(6 BYTE), 
	"ORIGIN_CONNUM" VARCHAR2(30 BYTE), 
	"ORIGIN_PINLIST" VARCHAR2(16 BYTE), 
	"ORIGIN_CONNTYPE" VARCHAR2(9 BYTE), 
	"ORIGIN_STATION" VARCHAR2(20 BYTE), 
	"ORIGIN_INSTR" VARCHAR2(3 BYTE), 
	"STATION_OLD" VARCHAR2(6 BYTE), 
	"APPROVERS" VARCHAR2(4000 BYTE), 
	"DEST_LOC" VARCHAR2(20 BYTE), 
	"DEST_RACK" VARCHAR2(40 BYTE), 
	"DEST_SIDE" VARCHAR2(4 BYTE), 
	"DEST_ELE" VARCHAR2(20 BYTE), 
	"DEST_SLOT" VARCHAR2(6 BYTE), 
	"DEST_CONNUM" VARCHAR2(30 BYTE), 
	"DEST_PINLIST" VARCHAR2(16 BYTE), 
	"DEST_CONNTYPE" VARCHAR2(9 BYTE), 
	"DEST_STATION" VARCHAR2(20 BYTE), 
	"DEST_INSTR" VARCHAR2(3 BYTE), 
	"FORMDEV_NAME" VARCHAR2(20 BYTE), 
	"USERID_LIST_TITLE" VARCHAR2(200 BYTE), 
	"PHASE" VARCHAR2(20 BYTE), 
	"BEAM_AREA" VARCHAR2(20 BYTE), 
	"SECTOR_GROUP" VARCHAR2(20 BYTE), 
	"SECTOR_AREA_SOURCE" VARCHAR2(20 BYTE), 
	"SECTOR_AREA_DEST" VARCHAR2(20 BYTE), 
	"PENETRATION" VARCHAR2(20 BYTE), 
	"PENETRATION_2" VARCHAR2(20 BYTE), 
	"MIN_LENGTH" VARCHAR2(20 BYTE), 
	"MAX_LENGTH" VARCHAR2(20 BYTE), 
	"ADDNL_LENGTH" VARCHAR2(20 BYTE), 
	"REVISION" VARCHAR2(20 BYTE), 
	"COMMENTS" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAPTAR_DATA" ;
--------------------------------------------------------
--  DDL for Table SMARTCAPTAR_INV
--------------------------------------------------------

  CREATE TABLE "CAPTAR"."SMARTCAPTAR_INV" 
   (	"CABLENUM" VARCHAR2(9 BYTE), 
	"CABLETYPE" VARCHAR2(15 BYTE), 
	"JOBNUM" VARCHAR2(10 BYTE), 
	"ENTEREDBY" VARCHAR2(12 BYTE), 
	"DATEENT" DATE, 
	"FUNC" VARCHAR2(120 BYTE), 
	"ACTIONREQ" VARCHAR2(1 BYTE), 
	"SYSTEM" VARCHAR2(50 BYTE), 
	"LENGTH" NUMBER(4,0), 
	"ROUTING" VARCHAR2(1000 BYTE), 
	"REV" NUMBER(2,0), 
	"LIST_NO" NUMBER(7,0), 
	"DWGNUM" VARCHAR2(200 BYTE), 
	"CABLEINV_ID" NUMBER, 
	"CREATED_BY" VARCHAR2(30 BYTE), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(30 BYTE), 
	"MODIFIED_DATE" DATE, 
	"DRAWING_TITLE" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAPTAR_DATA" ;
--------------------------------------------------------
--  DDL for Table SMARTCAPTAR_PROJECTS
--------------------------------------------------------

  CREATE TABLE "CAPTAR"."SMARTCAPTAR_PROJECTS" 
   (	"PROJECT_NAME" VARCHAR2(30 BYTE), 
	"PREFIX" VARCHAR2(3 BYTE), 
	"AREA" VARCHAR2(20 BYTE), 
	"ASSIGNED_USERS" VARCHAR2(200 BYTE), 
	"NUM_CABLES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAPTAR_DATA" ;
--------------------------------------------------------
--  DDL for Table SMARTCAPTAR_QUEUE
--------------------------------------------------------

  CREATE TABLE "CAPTAR"."SMARTCAPTAR_QUEUE" 
   (	"CABLENUM" VARCHAR2(9 BYTE), 
	"CABLETYPE" VARCHAR2(15 BYTE), 
	"JOBNUM" VARCHAR2(10 BYTE), 
	"ENTEREDBY" VARCHAR2(12 BYTE), 
	"DATEENT" TIMESTAMP (6), 
	"FUNC" VARCHAR2(120 BYTE), 
	"ACTIONREQ" VARCHAR2(1 BYTE), 
	"SYSTEM" VARCHAR2(50 BYTE), 
	"LENGTH" VARCHAR2(20 BYTE), 
	"ROUTING" VARCHAR2(1000 BYTE), 
	"LIST_NO" VARCHAR2(20 BYTE), 
	"DWGNUM" VARCHAR2(200 BYTE), 
	"CABLEINV_ID" VARCHAR2(20 BYTE), 
	"CREATED_BY" VARCHAR2(30 BYTE), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(30 BYTE), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"DRAWING_TITLE" VARCHAR2(80 BYTE), 
	"STATUS" VARCHAR2(9 BYTE), 
	"AREACODE" VARCHAR2(20 BYTE), 
	"ORIGIN_LOC" VARCHAR2(20 BYTE), 
	"ORIGIN_RACK" VARCHAR2(40 BYTE), 
	"ORIGIN_SIDE" VARCHAR2(4 BYTE), 
	"ORIGIN_ELE" VARCHAR2(20 BYTE), 
	"ORIGIN_SLOT" VARCHAR2(6 BYTE), 
	"ORIGIN_CONNUM" VARCHAR2(30 BYTE), 
	"ORIGIN_PINLIST" VARCHAR2(16 BYTE), 
	"ORIGIN_CONNTYPE" VARCHAR2(9 BYTE), 
	"ORIGIN_STATION" VARCHAR2(20 BYTE), 
	"ORIGIN_INSTR" VARCHAR2(3 BYTE), 
	"STATION_OLD" VARCHAR2(6 BYTE), 
	"APPROVERS" VARCHAR2(4000 BYTE), 
	"DEST_LOC" VARCHAR2(20 BYTE), 
	"DEST_RACK" VARCHAR2(40 BYTE), 
	"DEST_SIDE" VARCHAR2(4 BYTE), 
	"DEST_ELE" VARCHAR2(20 BYTE), 
	"DEST_SLOT" VARCHAR2(6 BYTE), 
	"DEST_CONNUM" VARCHAR2(30 BYTE), 
	"DEST_PINLIST" VARCHAR2(16 BYTE), 
	"DEST_CONNTYPE" VARCHAR2(9 BYTE), 
	"DEST_STATION" VARCHAR2(20 BYTE), 
	"DEST_INSTR" VARCHAR2(3 BYTE), 
	"FORMDEV_NAME" VARCHAR2(20 BYTE), 
	"USERID_LIST_TITLE" VARCHAR2(200 BYTE), 
	"PHASE" VARCHAR2(20 BYTE), 
	"BEAM_AREA" VARCHAR2(20 BYTE), 
	"SECTOR_GROUP" VARCHAR2(20 BYTE), 
	"SECTOR_AREA_SOURCE" VARCHAR2(20 BYTE), 
	"SECTOR_AREA_DEST" VARCHAR2(20 BYTE), 
	"PENETRATION" VARCHAR2(20 BYTE), 
	"PENETRATION_2" VARCHAR2(20 BYTE), 
	"MIN_LENGTH" VARCHAR2(20 BYTE), 
	"MAX_LENGTH" VARCHAR2(20 BYTE), 
	"ADDNL_LENGTH" VARCHAR2(20 BYTE), 
	"REVISION" VARCHAR2(20 BYTE), 
	"COMMENTS" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAPTAR_DATA" ;
--------------------------------------------------------
--  DDL for Table SMARTCAPTAR_UPLOAD
--------------------------------------------------------

  CREATE TABLE "CAPTAR"."SMARTCAPTAR_UPLOAD" 
   (	"CABLENUM" VARCHAR2(9 BYTE), 
	"CABLETYPE" VARCHAR2(15 BYTE), 
	"JOBNUM" VARCHAR2(10 BYTE), 
	"ENTEREDBY" VARCHAR2(12 BYTE), 
	"DATEENT" TIMESTAMP (6), 
	"FUNC" VARCHAR2(120 BYTE), 
	"ACTIONREQ" VARCHAR2(1 BYTE), 
	"SYSTEM" VARCHAR2(50 BYTE), 
	"LENGTH" VARCHAR2(20 BYTE), 
	"ROUTING" VARCHAR2(1000 BYTE), 
	"LIST_NO" VARCHAR2(20 BYTE), 
	"DWGNUM" VARCHAR2(200 BYTE), 
	"CABLEINV_ID" VARCHAR2(20 BYTE), 
	"CREATED_BY" VARCHAR2(30 BYTE), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(30 BYTE), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"DRAWING_TITLE" VARCHAR2(80 BYTE), 
	"STATUS" VARCHAR2(9 BYTE), 
	"AREACODE" VARCHAR2(20 BYTE), 
	"ORIGIN_LOC" VARCHAR2(20 BYTE), 
	"ORIGIN_RACK" VARCHAR2(40 BYTE), 
	"ORIGIN_SIDE" VARCHAR2(4 BYTE), 
	"ORIGIN_ELE" VARCHAR2(20 BYTE), 
	"ORIGIN_SLOT" VARCHAR2(6 BYTE), 
	"ORIGIN_CONNUM" VARCHAR2(30 BYTE), 
	"ORIGIN_PINLIST" VARCHAR2(16 BYTE), 
	"ORIGIN_CONNTYPE" VARCHAR2(9 BYTE), 
	"ORIGIN_STATION" VARCHAR2(20 BYTE), 
	"ORIGIN_INSTR" VARCHAR2(3 BYTE), 
	"STATION_OLD" VARCHAR2(6 BYTE), 
	"APPROVERS" VARCHAR2(4000 BYTE), 
	"DEST_LOC" VARCHAR2(20 BYTE), 
	"DEST_RACK" VARCHAR2(40 BYTE), 
	"DEST_SIDE" VARCHAR2(4 BYTE), 
	"DEST_ELE" VARCHAR2(20 BYTE), 
	"DEST_SLOT" VARCHAR2(6 BYTE), 
	"DEST_CONNUM" VARCHAR2(30 BYTE), 
	"DEST_PINLIST" VARCHAR2(16 BYTE), 
	"DEST_CONNTYPE" VARCHAR2(9 BYTE), 
	"DEST_STATION" VARCHAR2(20 BYTE), 
	"DEST_INSTR" VARCHAR2(3 BYTE), 
	"FORMDEV_NAME" VARCHAR2(20 BYTE), 
	"USERID_LIST_TITLE" VARCHAR2(200 BYTE), 
	"PHASE" VARCHAR2(20 BYTE), 
	"BEAM_AREA" VARCHAR2(20 BYTE), 
	"SECTOR_GROUP" VARCHAR2(20 BYTE), 
	"SECTOR_AREA_SOURCE" VARCHAR2(20 BYTE), 
	"SECTOR_AREA_DEST" VARCHAR2(20 BYTE), 
	"PENETRATION" VARCHAR2(20 BYTE), 
	"PENETRATION_2" VARCHAR2(20 BYTE), 
	"MIN_LENGTH" VARCHAR2(20 BYTE), 
	"MAX_LENGTH" VARCHAR2(20 BYTE), 
	"ADDNL_LENGTH" VARCHAR2(20 BYTE), 
	"REVISION" VARCHAR2(20 BYTE), 
	"COMMENTS" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAPTAR_DATA" ;
--------------------------------------------------------
--  DDL for Table SMARTCAPTAR_USERS
--------------------------------------------------------

  CREATE TABLE "CAPTAR"."SMARTCAPTAR_USERS" 
   (	"USERNAME" VARCHAR2(30 BYTE), 
	"PROJECTS" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAPTAR_DATA" ;
--------------------------------------------------------
--  Constraints for Table SMARTCAPTAR_APPROVED
--------------------------------------------------------

  ALTER TABLE "CAPTAR"."SMARTCAPTAR_APPROVED" MODIFY ("CABLENUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SMARTCAPTAR_HISTORY
--------------------------------------------------------

  ALTER TABLE "CAPTAR"."SMARTCAPTAR_HISTORY" MODIFY ("CABLENUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SMARTCAPTAR_INV
--------------------------------------------------------

  ALTER TABLE "CAPTAR"."SMARTCAPTAR_INV" MODIFY ("CABLENUM" NOT NULL ENABLE);
  ALTER TABLE "CAPTAR"."SMARTCAPTAR_INV" MODIFY ("REV" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SMARTCAPTAR_PROJECTS
--------------------------------------------------------

  ALTER TABLE "CAPTAR"."SMARTCAPTAR_PROJECTS" MODIFY ("PROJECT_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SMARTCAPTAR_QUEUE
--------------------------------------------------------

  ALTER TABLE "CAPTAR"."SMARTCAPTAR_QUEUE" MODIFY ("CABLENUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SMARTCAPTAR_UPLOAD
--------------------------------------------------------

  ALTER TABLE "CAPTAR"."SMARTCAPTAR_UPLOAD" MODIFY ("CABLENUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SMARTCAPTAR_USERS
--------------------------------------------------------

  ALTER TABLE "CAPTAR"."SMARTCAPTAR_USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
